// SAMPLE DATA — a fictional "FlowMax" water-pump catalogue. Invented for
// demonstration. Shows the SAME engine driving a completely different domain.
import type { Catalogue } from "../../catalogue/schema";

export const catalogue: Catalogue = {
  categoryLabels: {
    domestic: "Domestic",
    agricultural: "Agricultural",
    industrial: "Industrial",
  },

  fields: {
    familyName: "Product Line",
    partNumber: "Model",
    partUrl: "url",
    keyword: ["Product Line", "Type", "Use Cases", "Description"],
  },

  // Single-level catalogue: all products live in `parts`.
  families: [],

  parts: [
    {
      category: "domestic",
      "Product Line": "HomeFlow",
      "Model": "FM-HF-200",
      "Type": "Booster",
      "Flow Rate (L/min)": "40",
      "Max Head (m)": "35",
      "Power (W)": "200",
      "Inlet/Outlet (in)": "1",
      "Material": "Stainless Steel",
      "Voltage (V)": "230",
      "Self Priming": "Yes",
      "Price (USD)": "180",
      "Use Cases": "Home water boosting, Showers, Garden hoses",
      "url": "https://example.com/flowmax/fm-hf-200",
      "Description": "Compact self-priming booster pump for household water pressure.",
    },
    {
      category: "domestic",
      "Product Line": "HomeFlow",
      "Model": "FM-HF-400",
      "Type": "Booster",
      "Flow Rate (L/min)": "70",
      "Max Head (m)": "45",
      "Power (W)": "400",
      "Inlet/Outlet (in)": "1.25",
      "Material": "Stainless Steel",
      "Voltage (V)": "230",
      "Self Priming": "Yes",
      "Price (USD)": "260",
      "Use Cases": "Multi-bathroom homes, Pressure boosting",
      "url": "https://example.com/flowmax/fm-hf-400",
      "Description": "Higher-capacity booster for larger homes with multiple outlets.",
    },
    {
      category: "agricultural",
      "Product Line": "AgriJet",
      "Model": "FM-AJ-1500",
      "Type": "Centrifugal",
      "Flow Rate (L/min)": "300",
      "Max Head (m)": "55",
      "Power (W)": "1500",
      "Inlet/Outlet (in)": "2",
      "Material": "Cast Iron",
      "Voltage (V)": "400",
      "Self Priming": "No",
      "Price (USD)": "640",
      "Use Cases": "Irrigation, Field watering, Water transfer",
      "url": "https://example.com/flowmax/fm-aj-1500",
      "Description": "Three-phase centrifugal pump for high-flow agricultural irrigation.",
    },
    {
      category: "agricultural",
      "Product Line": "AgriJet",
      "Model": "FM-AJ-2200",
      "Type": "Centrifugal",
      "Flow Rate (L/min)": "450",
      "Max Head (m)": "70",
      "Power (W)": "2200",
      "Inlet/Outlet (in)": "2.5",
      "Material": "Cast Iron",
      "Voltage (V)": "400",
      "Self Priming": "No",
      "Price (USD)": "880",
      "Use Cases": "Large-scale irrigation, Drainage",
      "url": "https://example.com/flowmax/fm-aj-2200",
      "Description": "High-head centrifugal pump for demanding irrigation and transfer duties.",
    },
    {
      category: "industrial",
      "Product Line": "DeepDraw",
      "Model": "FM-DD-1100",
      "Type": "Submersible",
      "Flow Rate (L/min)": "120",
      "Max Head (m)": "90",
      "Power (W)": "1100",
      "Inlet/Outlet (in)": "1.5",
      "Material": "Stainless Steel",
      "Voltage (V)": "230",
      "Self Priming": "Yes",
      "Price (USD)": "520",
      "Use Cases": "Borehole, Well extraction, Deep water",
      "url": "https://example.com/flowmax/fm-dd-1100",
      "Description": "Narrow-diameter submersible pump for boreholes and deep wells.",
    },
    {
      category: "industrial",
      "Product Line": "DrainPro",
      "Model": "FM-DP-750",
      "Type": "Submersible",
      "Flow Rate (L/min)": "250",
      "Max Head (m)": "12",
      "Power (W)": "750",
      "Inlet/Outlet (in)": "2",
      "Material": "Thermoplastic",
      "Voltage (V)": "230",
      "Self Priming": "No",
      "Price (USD)": "210",
      "Use Cases": "Drainage, Flood water, Sumps",
      "url": "https://example.com/flowmax/fm-dp-750",
      "Description": "High-flow, low-head submersible drainage pump for sumps and flooding.",
    },
  ],
};
