// SAMPLE DATA — a fictional "Crema" espresso-machine catalogue. Invented for
// demonstration. A consumer-product domain on the same engine.
import type { Catalogue } from "../../catalogue/schema";

export const catalogue: Catalogue = {
  categoryLabels: {
    manual: "Manual",
    "semi-automatic": "Semi-automatic",
    "super-automatic": "Super-automatic",
  },

  fields: {
    familyName: "Range",
    partNumber: "Model",
    partUrl: "url",
    keyword: ["Range", "Type", "Use Cases", "Description"],
  },

  families: [],

  parts: [
    {
      category: "manual",
      "Range": "Levetta",
      "Model": "CR-LV-01",
      "Type": "Manual",
      "Pressure Gauge": "Yes",
      "Touch Screen": "No",
      "Built-in Grinder": "No",
      "Milk Frother": "Steam wand",
      "Boiler Type": "Single boiler",
      "Pressure (bar)": "9",
      "Water Tank (L)": "1.5",
      "Price (USD)": "650",
      "Use Cases": "Enthusiasts, Lever control, Latte art",
      "url": "https://example.com/crema/cr-lv-01",
      "Description": "Manual lever machine with pressure gauge and steam wand for hands-on espresso.",
    },
    {
      category: "semi-automatic",
      "Range": "Barista",
      "Model": "CR-BA-10",
      "Type": "Semi-automatic",
      "Pressure Gauge": "Yes",
      "Touch Screen": "No",
      "Built-in Grinder": "No",
      "Milk Frother": "Steam wand",
      "Boiler Type": "Single boiler",
      "Pressure (bar)": "15",
      "Water Tank (L)": "1.8",
      "Price (USD)": "420",
      "Use Cases": "Home baristas, Espresso, Cappuccino",
      "url": "https://example.com/crema/cr-ba-10",
      "Description": "Affordable semi-automatic with a pressure gauge and steam wand; pair with a grinder.",
    },
    {
      category: "semi-automatic",
      "Range": "Barista",
      "Model": "CR-BA-20",
      "Type": "Semi-automatic",
      "Pressure Gauge": "Yes",
      "Touch Screen": "Yes",
      "Built-in Grinder": "Yes",
      "Milk Frother": "Steam wand",
      "Boiler Type": "Dual boiler",
      "Pressure (bar)": "15",
      "Water Tank (L)": "2.0",
      "Price (USD)": "1100",
      "Use Cases": "Home baristas, Latte art, All-in-one",
      "url": "https://example.com/crema/cr-ba-20",
      "Description": "Semi-automatic with built-in grinder, dual boiler, and a touch display.",
    },
    {
      category: "super-automatic",
      "Range": "Auto",
      "Model": "CR-AU-30",
      "Type": "Super-automatic",
      "Pressure Gauge": "No",
      "Touch Screen": "Yes",
      "Built-in Grinder": "Yes",
      "Milk Frother": "Automatic",
      "Boiler Type": "Thermoblock",
      "Pressure (bar)": "19",
      "Water Tank (L)": "1.8",
      "Price (USD)": "900",
      "Use Cases": "One-touch, Offices, Convenience",
      "url": "https://example.com/crema/cr-au-30",
      "Description": "Bean-to-cup super-automatic: grind, brew, and froth at the touch of a button.",
    },
    {
      category: "super-automatic",
      "Range": "Auto",
      "Model": "CR-AU-50",
      "Type": "Super-automatic",
      "Pressure Gauge": "No",
      "Touch Screen": "Yes",
      "Built-in Grinder": "Yes",
      "Milk Frother": "Automatic",
      "Boiler Type": "Dual boiler",
      "Pressure (bar)": "19",
      "Water Tank (L)": "2.2",
      "Price (USD)": "1600",
      "Use Cases": "Premium, One-touch lattes, Profiles",
      "url": "https://example.com/crema/cr-au-50",
      "Description": "Premium super-automatic with dual boiler, drink profiles, and full touchscreen.",
    },
    {
      category: "manual",
      "Range": "Levetta",
      "Model": "CR-LV-02",
      "Type": "Manual",
      "Pressure Gauge": "No",
      "Touch Screen": "No",
      "Built-in Grinder": "No",
      "Milk Frother": "Steam wand",
      "Boiler Type": "Single boiler",
      "Pressure (bar)": "9",
      "Water Tank (L)": "1.2",
      "Price (USD)": "480",
      "Use Cases": "Compact, Enthusiasts, Small kitchens",
      "url": "https://example.com/crema/cr-lv-02",
      "Description": "Compact manual lever machine without a gauge — pure, minimal espresso craft.",
    },
  ],
};
