// SAMPLE DATA — a fictional "Acme" wireless-chip catalogue. Invented for
// demonstration; any resemblance to real parts is coincidental.
import type { Catalogue } from "../../catalogue/schema";

export const catalogue: Catalogue = {
  categoryLabels: {
    bluetooth: "Bluetooth",
    multiprotocol: "Multi-protocol",
    wifi: "Wi-Fi",
  },

  fields: {
    familyName: "Product Family",
    partNumber: "Part Number",
    partUrl: "url",
    keyword: ["Product Family", "Protocols", "Use Cases", "Description"],
  },

  families: [
    {
      category: "bluetooth",
      "Product Family": "Acme W1",
      "Type": "SoC",
      "Protocols": "Bluetooth LE",
      "BLE Version": "5.4",
      "MCU Core": "Arm Cortex-M4",
      "Flash (KB)": "512 – 1024",
      "RAM (KB)": "64 – 128",
      "Has Audio": "No",
      "Use Cases": "Wearables, Sensors, Remote Controls",
      "Variants  /  Count": "2 variants",
    },
    {
      category: "bluetooth",
      "Product Family": "Acme W2",
      "Type": "SoC",
      "Protocols": "Bluetooth LE, Bluetooth Classic",
      "BLE Version": "5.4",
      "MCU Core": "Arm Cortex-M33",
      "Flash (KB)": "2048 – 4096",
      "RAM (KB)": "512",
      "Has Audio": "Yes",
      "Use Cases": "Headphones, Speakers, Wireless Audio",
      "Variants  /  Count": "2 variants",
    },
    {
      category: "multiprotocol",
      "Product Family": "Acme M3",
      "Type": "SoC",
      "Protocols": "Bluetooth LE, Zigbee, Thread, Matter",
      "BLE Version": "6.0",
      "MCU Core": "Arm Cortex-M33",
      "Flash (KB)": "1024 – 2048",
      "RAM (KB)": "256 – 512",
      "Has Audio": "No",
      "Use Cases": "Smart Home, Lighting, Sensors",
      "Variants  /  Count": "2 variants",
    },
    {
      category: "multiprotocol",
      "Product Family": "Acme M3M",
      "Type": "Module",
      "Protocols": "Bluetooth LE, Zigbee, Thread, Matter",
      "BLE Version": "6.0",
      "MCU Core": "Arm Cortex-M33",
      "Flash (KB)": "2048",
      "RAM (KB)": "512",
      "Has Audio": "No",
      "Use Cases": "Smart Home, Gateways",
      "Variants  /  Count": "1 variant",
    },
    {
      category: "wifi",
      "Product Family": "Acme F5M",
      "Type": "Module",
      "Protocols": "Wi-Fi 6, Bluetooth LE",
      "BLE Version": "5.4",
      "MCU Core": "RISC-V",
      "Flash (KB)": "4096",
      "RAM (KB)": "512",
      "Has Audio": "No",
      "Use Cases": "Smart Home, Appliances, Gateways",
      "Variants  /  Count": "1 variant",
    },
  ],

  parts: [
    {
      category: "bluetooth",
      "Product Family": "Acme W1",
      "Part Number": "ACM-W110",
      "Type": "SoC",
      "Protocols": "Bluetooth LE",
      "BLE Version": "5.4",
      "Has Matter": "No",
      "Has Zigbee": "No",
      "Has Thread": "No",
      "Has Wi-Fi": "No",
      "Has BT Classic": "No",
      "Has Audio": "No",
      "MCU Core": "Arm Cortex-M4",
      "Flash (KB)": "512",
      "RAM (KB)": "64",
      "GPIO": "26",
      "Package Size (mm)": "QFN32, 5x5",
      "Supply Voltage": "1.8 – 3.6 V",
      "Use Cases": "Wearables, Remote Controls",
      "url": "https://example.com/acme/acm-w110",
      "Description": "Entry-level Bluetooth LE SoC for low-power wearables and remotes.",
    },
    {
      category: "bluetooth",
      "Product Family": "Acme W1",
      "Part Number": "ACM-W120",
      "Type": "SoC",
      "Protocols": "Bluetooth LE",
      "BLE Version": "5.4",
      "Has Matter": "No",
      "Has Zigbee": "No",
      "Has Thread": "No",
      "Has Wi-Fi": "No",
      "Has BT Classic": "No",
      "Has Audio": "No",
      "MCU Core": "Arm Cortex-M4",
      "Flash (KB)": "1024",
      "RAM (KB)": "128",
      "GPIO": "38",
      "Package Size (mm)": "QFN48, 6x6",
      "Supply Voltage": "1.8 – 3.6 V",
      "Use Cases": "Sensors, Smart Home",
      "url": "https://example.com/acme/acm-w120",
      "Description": "Higher-memory Bluetooth LE SoC with more GPIO for richer sensor designs.",
    },
    {
      category: "bluetooth",
      "Product Family": "Acme W2",
      "Part Number": "ACM-W210",
      "Type": "SoC",
      "Protocols": "Bluetooth LE, Bluetooth Classic",
      "BLE Version": "5.4",
      "Has Matter": "No",
      "Has Zigbee": "No",
      "Has Thread": "No",
      "Has Wi-Fi": "No",
      "Has BT Classic": "Yes",
      "Has Audio": "Yes",
      "MCU Core": "Arm Cortex-M33",
      "Flash (KB)": "4096",
      "RAM (KB)": "512",
      "GPIO": "30",
      "Package Size (mm)": "QFN48, 6x6",
      "Supply Voltage": "3.0 – 4.3 V",
      "Use Cases": "Headphones, Wireless Audio",
      "url": "https://example.com/acme/acm-w210",
      "Description": "Audio-focused SoC with Bluetooth Classic for headsets and speakers.",
    },
    {
      category: "multiprotocol",
      "Product Family": "Acme M3",
      "Part Number": "ACM-M310",
      "Type": "SoC",
      "Protocols": "Bluetooth LE, Zigbee, Thread, Matter",
      "BLE Version": "6.0",
      "Has Matter": "Yes",
      "Has Zigbee": "Yes",
      "Has Thread": "Yes",
      "Has Wi-Fi": "No",
      "Has BT Classic": "No",
      "Has Audio": "No",
      "MCU Core": "Arm Cortex-M33",
      "Flash (KB)": "2048",
      "RAM (KB)": "512",
      "GPIO": "40",
      "Package Size (mm)": "QFN48, 6x6",
      "Supply Voltage": "1.8 – 3.6 V",
      "Use Cases": "Smart Home, Lighting",
      "url": "https://example.com/acme/acm-m310",
      "Description": "Flagship multi-protocol SoC running Matter over Thread and Zigbee concurrently.",
    },
    {
      category: "multiprotocol",
      "Product Family": "Acme M3M",
      "Part Number": "ACM-M3M-01",
      "Type": "Module",
      "Protocols": "Bluetooth LE, Zigbee, Thread, Matter",
      "BLE Version": "6.0",
      "Has Matter": "Yes",
      "Has Zigbee": "Yes",
      "Has Thread": "Yes",
      "Has Wi-Fi": "No",
      "Has BT Classic": "No",
      "Has Audio": "No",
      "MCU Core": "Arm Cortex-M33",
      "Flash (KB)": "2048",
      "RAM (KB)": "512",
      "GPIO": "32",
      "Package Size (mm)": "14 x 10 x 2",
      "Supply Voltage": "1.8 – 3.6 V",
      "Use Cases": "Smart Home, Gateways",
      "url": "https://example.com/acme/acm-m3m-01",
      "Description": "Certified, antenna-integrated module on the M3 die — Matter connectivity with no RF design.",
    },
    {
      category: "wifi",
      "Product Family": "Acme F5M",
      "Part Number": "ACM-F5M-01",
      "Type": "Module",
      "Protocols": "Wi-Fi 6, Bluetooth LE",
      "BLE Version": "5.4",
      "Has Matter": "Yes",
      "Has Zigbee": "No",
      "Has Thread": "Yes",
      "Has Wi-Fi": "Yes",
      "Has BT Classic": "No",
      "Has Audio": "No",
      "MCU Core": "RISC-V",
      "Flash (KB)": "4096",
      "RAM (KB)": "512",
      "GPIO": "20",
      "Package Size (mm)": "18 x 14 x 2",
      "Supply Voltage": "3.0 – 3.6 V",
      "Use Cases": "Appliances, Gateways",
      "url": "https://example.com/acme/acm-f5m-01",
      "Description": "Wi-Fi 6 + Bluetooth LE module that bridges local mesh devices to the cloud.",
    },
  ],
};
